### ISSUE TITLE
你好请问怎么判断模型是否运行完呢？

### ISSUE THREAD

**Issue by beam-fly** [SWU-CS-MediaLab/SCAHN#3]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    run(config_path="/home/b3/demo_1/deep-cross-modal-hashing-master/default_config.yml")
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/run.py", line 42, in run
    get_train(method,data_name.upper(),img_dir,bit=bit, batch_size=batch_size, cuda=cuda, **kwargs)
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/run.py", line 51, in get_train
    train(dataset_name,img_dir, bit, **kwargs)
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/training/SCAHN.py", line 269, in train
    trainer.train()
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/training/SCAHN.py", line 169, in train
    self.valid(epoch)
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/training/SCAHN.py", line 238, in valid
    return_hash=True)
ValueError: too many values to unpack (expected 6)这个报错一直改不好，请问是需要改代码还是改config呢？

**Comment by beam-fly** [comment]
好吧好像是我visdom启动失败了，打扰了

**Comment by beam-fly** [comment]
ValueError: too many values to unpack (expected 6)
